# Generated by Django 2.1 on 2018-11-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0002_auto_20181107_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
